

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appwish
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=02ogigi93920laagA2

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=appwish
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=02ogigi93920laagA2
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: